# Generated by Django 2.0.6 on 2018-06-19 05:40

from django.db import migrations, models
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', privates.fields.PrivateMediaFileField(storage=privates.storages.PrivateMediaFileSystemStorage(), upload_to='')),
            ],
        ),
    ]
