# Generated by Django 5.1.6 on 2025-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_file2"),
    ]

    operations = [
        migrations.CreateModel(
            name="File3",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.file",),
        ),
        migrations.CreateModel(
            name="File4",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.file",),
        ),
    ]
