# Generated by Django 4.2 on 2025-07-09 08:21

from django.db import migrations, models
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_file3_file4"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    privates.fields.PrivateMediaFileField(
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
