# Generated by Django 6.0.5 on 2026-05-15 20:20

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_file3_file4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=privates.fields.PrivateMediaFileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="file",
            name="image",
            field=privates.fields.PrivateMediaImageField(upload_to=""),
        ),
    ]
