# Generated by Django 6.0.5 on 2026-05-14 11:52

import pathlib

import django.core.files.storage
from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_file3_file4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=privates.fields.PrivateMediaFileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/protected/",
                    location=pathlib.PurePosixPath(
                        "/home/bbt/code/django-privates/testapp/private_media"
                    ),
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="image",
            field=privates.fields.PrivateMediaImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/protected/",
                    location=pathlib.PurePosixPath(
                        "/home/bbt/code/django-privates/testapp/private_media"
                    ),
                ),
                upload_to="",
            ),
        ),
    ]
